import "./globals.css";
import Metadata from "next";
import { Inter } from "next/font/google";
import Header from "./components/header/header";
import { Footer } from "./components/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Conexão brasil Espanha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
